### ISSUE TITLE
Variable declarations in for...in statements cause syntax errors

### ISSUE THREAD

**Issue by toolness** [toolness/slowmo-js#13]
Originally reported by @ericperez in #4, the following causes a syntax error:

``` javascript
for (var i in [1,2,3]) {
  console.log(i);
}
```

**Comment by wonsuchai** [comment]
https://github.com/toolness/slowmo-js/issues/13#issue-14234719

**Comment by wonsuchai** [comment]
![box2-home](https://user-images.githubusercontent.com/1408961/119401944-6496f400-bd06-11eb-9d97-03bfedb0eb2b.png)
