### ISSUE TITLE
Array methods, doesn't work

### ISSUE THREAD

**Issue by saebekassebil** [toolness/slowmo-js#4]
``` javascript
[0,1,2,3,4,5].map(function(n) {
  return n * n;
});
```

fails with `TypeError: Array.prototype.map called on null or undefined`. And the same for any other array method (`forEach`, `filter`, etc). Seems the array literal isn't parsed properly.

**Comment by cha0s** [comment]
String methods are also broken, tested split and replace.

**Comment by ericperez** [comment]
The code below does not parse correctly. I either get "SyntaxError: Unexpected token 'in'" message in Safari or "SyntaxError: syntax error" in Firefox.

```
var foo = [1, 2, 'a', 'b'];
for (var i in foo) {
    alert(foo[i]);
}
```

**Comment by toolness** [comment]
Thanks for the reports! I think I've fixed the bug.

@ericperez, your example is actually a separate bug, which I've just filed as #13.

**Comment by wonsuchai** [comment]
[0,1,2,3,4,5].map(function(n) {
  return n * n;
});
