### ISSUE TITLE
Would be even awesomer if it animated the steps so it plays like a movie

### ISSUE THREAD

**Issue by alexrothenberg** [toolness/slowmo-js#8]
This is fantastic but just in case you're looking for more ideas mine's here.

Great job!

--alex

**Comment by michaelficarra** [comment]
Quoting the README:

> <h2>Design Notes</h2>
> 
> I originally wanted to use <a href="http://popcornjs.org/">Popcorn</a> to generate a movie of the user's code being executed, but given <a href="https://www.edwardtufte.com/tufte/">Edward Tufte</a>'s belief that it's usually better to have information adjacent in space rather than stacked in time--which is yet another problem with traditional debuggers--I decided to make the visualization purely spatial, rather than temporal.

**Comment by alexrothenberg** [comment]
I should have read the readme :)
